//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillboardApp.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class conauth
    {
        public int authId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string loginKey { get; set; }
        public int userId { get; set; }
        public int profileId { get; set; }
        public int statusId { get; set; }
        public int customerId { get; set; }
        public int supplierId { get; set; }
        public int employeeId { get; set; }
        public int branchId { get; set; }
        public int life { get; set; }
        public int createbyId { get; set; }
        public System.DateTime createdt { get; set; }
        public int writebyId { get; set; }
        public int writedt { get; set; }
        public int companyId { get; set; }
    }
}
