//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillboardApp.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class concompany
    {
        public int companyId { get; set; }
        public string logo { get; set; }
        public System.DateTime regDate { get; set; }
        public string companyNo { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public string companyName { get; set; }
        public string companyInitials { get; set; }
        public string taxpinNo { get; set; }
        public string branches { get; set; }
        public string memo { get; set; }
        public int age { get; set; }
        public int countryId { get; set; }
        public int industryId { get; set; }
        public string physicalAddress { get; set; }
        public string primaryMobileNo { get; set; }
        public string otherMobileNo { get; set; }
        public string primaryLandline { get; set; }
        public string otherLandline { get; set; }
        public string primaryEmail { get; set; }
        public string otherEmail { get; set; }
        public string boxAddress { get; set; }
        public string boxAddressCode { get; set; }
        public string boxAddressTown { get; set; }
        public string websiteUrl { get; set; }
        public int life { get; set; }
        public int createbyId { get; set; }
        public Nullable<System.DateTime> createdt { get; set; }
        public int writebyId { get; set; }
        public Nullable<System.DateTime> writedt { get; set; }
    }
}
