//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillboardApp.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class conindustry
    {
        public int industryId { get; set; }
        public string industry { get; set; }
        public string industryCode { get; set; }
        public int life { get; set; }
        public int createbyId { get; set; }
        public System.DateTime createdt { get; set; }
        public int writebyId { get; set; }
        public System.DateTime writedt { get; set; }
        public int companyId { get; set; }
    }
}
