//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillboardApp.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class conobject
    {
        public int objectId { get; set; }
        public string objectCode { get; set; }
        public int level { get; set; }
        public int parentObjectId { get; set; }
        public int isreport { get; set; }
        public int isgraph { get; set; }
        public int isbuttonselect { get; set; }
        public int isbuttonselectwithmenu { get; set; }
        public int hasnotification { get; set; }
        public int hasreportsubmenu { get; set; }
        public int life { get; set; }
        public int createbyId { get; set; }
        public Nullable<System.DateTime> createdt { get; set; }
        public int writebyId { get; set; }
        public System.DateTime writedt { get; set; }
        public string objectName { get; set; }
    }
}
