//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillboardApp.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class conobjectright
    {
        public int objectRightsId { get; set; }
        public int profileId { get; set; }
        public int objectId { get; set; }
        public int canview { get; set; }
        public int canadd { get; set; }
        public int canedit { get; set; }
        public int candel { get; set; }
        public int canauthorize { get; set; }
        public int canapprove { get; set; }
        public int canexport { get; set; }
        public int life { get; set; }
        public int createbyId { get; set; }
        public System.DateTime createdt { get; set; }
        public int writebyId { get; set; }
        public Nullable<System.DateTime> writedt { get; set; }
    }
}
