//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillboardApp.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class conobjectscaption
    {
        public int objectCaptionId { get; set; }
        public int objectId { get; set; }
        public int industryId { get; set; }
        public string objectCaptionName { get; set; }
        public string icons { get; set; }
        public string islarge { get; set; }
        public int quicklink { get; set; }
        public string setpath { get; set; }
        public string reportpath { get; set; }
        public int objectCaptionSort { get; set; }
        public int available { get; set; }
        public int life { get; set; }
        public int createbyId { get; set; }
        public Nullable<System.DateTime> createdt { get; set; }
        public int writebyId { get; set; }
        public Nullable<System.DateTime> writedt { get; set; }
        public int companyId { get; set; }
    }
}
