//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillboardApp.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class conuserrecovery
    {
        public int userRecoveryId { get; set; }
        public int userId { get; set; }
        public int userRecoveryTypeId { get; set; }
        public string recoveryCode { get; set; }
        public Nullable<System.DateTime> expiryDateTime { get; set; }
        public int isRecovered { get; set; }
        public System.DateTime dateTimeRecovered { get; set; }
        public int life { get; set; }
        public int createbyId { get; set; }
        public System.DateTime createdt { get; set; }
        public int writebyId { get; set; }
        public System.DateTime writedt { get; set; }
        public int companyId { get; set; }
    }
}
