//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillboardApp.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class conuser
    {
        public int userId { get; set; }
        public string surname { get; set; }
        public string otherName { get; set; }
        public string recoveryphone { get; set; }
        public string recoveryemail { get; set; }
        public int profileId { get; set; }
        public int status { get; set; }
        public int companyId { get; set; }
        public int life { get; set; }
        public int createbyId { get; set; }
        public Nullable<System.DateTime> createdt { get; set; }
        public int writebyId { get; set; }
        public Nullable<System.DateTime> writedt { get; set; }
    }
}
