//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillboardApp.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Face
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Face()
        {
            this.Adverts = new HashSet<Advert>();
            this.FaceImages = new HashSet<FaceImage>();
        }
    
        public int FaceID { get; set; }
        public int FaceSizeID { get; set; }
        public int FaceConditionID { get; set; }
        public int FaceBoundID { get; set; }
        public int FacePositionID { get; set; }
        public int FaceOrientationID { get; set; }
        public int StructureID { get; set; }
        public int FaceOccupancyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advert> Adverts { get; set; }
        public virtual FaceBound FaceBound { get; set; }
        public virtual FaceCondition FaceCondition { get; set; }
        public virtual FaceOccupancy FaceOccupancy { get; set; }
        public virtual FaceOrientation FaceOrientation { get; set; }
        public virtual FacePosition FacePosition { get; set; }
        public virtual FaceSize FaceSize { get; set; }
        public virtual Structure Structure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaceImage> FaceImages { get; set; }
        public virtual FaceVisibilityRating FaceVisibilityRating { get; set; }
    }
}
