// <auto-generated />
namespace BillboardApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DesignUpdates_V35 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DesignUpdates_V35));
        
        string IMigrationMetadata.Id
        {
            get { return "201709202210212_DesignUpdates_V35"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
