//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillboardApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constituency
    {
        public int ConstituencyID { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Geom { get; set; }
    }
}
