//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillboardApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaceVisibilityRating
    {
        public int FaceVisibilityRatingID { get; set; }
        public Nullable<double> VegetationCoverScore { get; set; }
        public Nullable<double> SightLightingScore { get; set; }
        public Nullable<double> BacklightScore { get; set; }
        public Nullable<double> UnlightScore { get; set; }
        public Nullable<double> TrafficScore { get; set; }
        public Nullable<double> ClutterScore { get; set; }
    
        public virtual Face Face { get; set; }
    }
}
