//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaceImage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FaceImage()
        {
            this.Faces = new HashSet<Face>();
            this.Faces1 = new HashSet<Face>();
        }
    
        public int FaceImageID { get; set; }
        public byte[] Image { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<int> Face_FaceID { get; set; }
        public Nullable<int> Face_FaceID1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces1 { get; set; }
        public virtual Face Face { get; set; }
        public virtual Face Face1 { get; set; }
    }
}
