//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaceVisibilityRating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FaceVisibilityRating()
        {
            this.Faces = new HashSet<Face>();
        }
    
        public int FaceVisibilityRatingID { get; set; }
        public Nullable<double> VegetationCoverScore { get; set; }
        public Nullable<double> SightLightingScore { get; set; }
        public Nullable<double> BacklightScore { get; set; }
        public Nullable<double> UnlightScore { get; set; }
        public Nullable<double> TrafficScore { get; set; }
        public Nullable<double> ClutterScore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces { get; set; }
    }
}
