//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaceImage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FaceImage()
        {
            this.Faces = new HashSet<Face>();
            this.Faces1 = new HashSet<Face>();
            this.Faces2 = new HashSet<Face>();
            this.Faces11 = new HashSet<Face>();
            this.Faces21 = new HashSet<Face>();
            this.Faces3 = new HashSet<Face>();
            this.Faces4 = new HashSet<Face>();
            this.Faces12 = new HashSet<Face>();
            this.Faces22 = new HashSet<Face>();
            this.Faces31 = new HashSet<Face>();
            this.Faces41 = new HashSet<Face>();
            this.Faces5 = new HashSet<Face>();
            this.Faces6 = new HashSet<Face>();
            this.Faces7 = new HashSet<Face>();
            this.Faces8 = new HashSet<Face>();
            this.Faces9 = new HashSet<Face>();
            this.Faces10 = new HashSet<Face>();
            this.Faces111 = new HashSet<Face>();
            this.Faces13 = new HashSet<Face>();
            this.Faces14 = new HashSet<Face>();
            this.Faces23 = new HashSet<Face>();
            this.Faces32 = new HashSet<Face>();
            this.Faces42 = new HashSet<Face>();
            this.Faces51 = new HashSet<Face>();
            this.Faces61 = new HashSet<Face>();
            this.Faces71 = new HashSet<Face>();
            this.Faces81 = new HashSet<Face>();
            this.Faces91 = new HashSet<Face>();
            this.Faces101 = new HashSet<Face>();
            this.Faces112 = new HashSet<Face>();
            this.Faces121 = new HashSet<Face>();
            this.Faces131 = new HashSet<Face>();
            this.Faces141 = new HashSet<Face>();
            this.Faces15 = new HashSet<Face>();
            this.Faces16 = new HashSet<Face>();
            this.Faces17 = new HashSet<Face>();
            this.Faces18 = new HashSet<Face>();
            this.Faces19 = new HashSet<Face>();
            this.Faces20 = new HashSet<Face>();
            this.Faces211 = new HashSet<Face>();
            this.Faces221 = new HashSet<Face>();
            this.Faces231 = new HashSet<Face>();
            this.Faces24 = new HashSet<Face>();
            this.Faces25 = new HashSet<Face>();
            this.Faces26 = new HashSet<Face>();
            this.Faces27 = new HashSet<Face>();
            this.Faces28 = new HashSet<Face>();
            this.Faces29 = new HashSet<Face>();
            this.Faces30 = new HashSet<Face>();
            this.Faces311 = new HashSet<Face>();
            this.Faces321 = new HashSet<Face>();
            this.Faces33 = new HashSet<Face>();
            this.Faces34 = new HashSet<Face>();
            this.Faces35 = new HashSet<Face>();
        }
    
        public int FaceImageID { get; set; }
        public byte[] Image { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<int> Face_FaceID { get; set; }
        public Nullable<int> Face_FaceID1 { get; set; }
        public Nullable<int> Face_FaceID2 { get; set; }
        public Nullable<int> Face1_FaceID { get; set; }
        public Nullable<int> Face_FaceID3 { get; set; }
        public Nullable<int> Face_FaceID4 { get; set; }
        public Nullable<int> Face_FaceID5 { get; set; }
        public Nullable<int> Face1_FaceID1 { get; set; }
        public Nullable<int> Face11_FaceID { get; set; }
        public Nullable<int> Face2_FaceID { get; set; }
        public Nullable<int> Face21_FaceID { get; set; }
        public Nullable<int> Face3_FaceID { get; set; }
        public Nullable<int> Face_FaceID6 { get; set; }
        public Nullable<int> Face_FaceID7 { get; set; }
        public Nullable<int> Face_FaceID8 { get; set; }
        public Nullable<int> Face_FaceID9 { get; set; }
        public Nullable<int> Face_FaceID10 { get; set; }
        public Nullable<int> Face_FaceID11 { get; set; }
        public Nullable<int> Face_FaceID12 { get; set; }
        public Nullable<int> Face1_FaceID2 { get; set; }
        public Nullable<int> Face10_FaceID { get; set; }
        public Nullable<int> Face11_FaceID1 { get; set; }
        public Nullable<int> Face111_FaceID { get; set; }
        public Nullable<int> Face12_FaceID { get; set; }
        public Nullable<int> Face2_FaceID1 { get; set; }
        public Nullable<int> Face21_FaceID1 { get; set; }
        public Nullable<int> Face22_FaceID { get; set; }
        public Nullable<int> Face3_FaceID1 { get; set; }
        public Nullable<int> Face31_FaceID { get; set; }
        public Nullable<int> Face4_FaceID { get; set; }
        public Nullable<int> Face41_FaceID { get; set; }
        public Nullable<int> Face5_FaceID { get; set; }
        public Nullable<int> Face6_FaceID { get; set; }
        public Nullable<int> Face7_FaceID { get; set; }
        public Nullable<int> Face8_FaceID { get; set; }
        public Nullable<int> Face9_FaceID { get; set; }
        public Nullable<int> Face_FaceID13 { get; set; }
        public Nullable<int> Face_FaceID14 { get; set; }
        public Nullable<int> Face_FaceID15 { get; set; }
        public Nullable<int> Face_FaceID16 { get; set; }
        public Nullable<int> Face_FaceID17 { get; set; }
        public Nullable<int> Face_FaceID18 { get; set; }
        public Nullable<int> Face_FaceID19 { get; set; }
        public Nullable<int> Face_FaceID20 { get; set; }
        public Nullable<int> Face_FaceID21 { get; set; }
        public Nullable<int> Face_FaceID22 { get; set; }
        public Nullable<int> Face_FaceID23 { get; set; }
        public Nullable<int> Face_FaceID24 { get; set; }
        public Nullable<int> Face_FaceID25 { get; set; }
        public Nullable<int> Face_FaceID26 { get; set; }
        public Nullable<int> Face_FaceID27 { get; set; }
        public Nullable<int> Face_FaceID28 { get; set; }
        public Nullable<int> Face_FaceID29 { get; set; }
        public Nullable<int> Face_FaceID30 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces1 { get; set; }
        public virtual Face Face { get; set; }
        public virtual Face Face1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces3 { get; set; }
        public virtual Face Face2 { get; set; }
        public virtual Face Face11 { get; set; }
        public virtual Face Face21 { get; set; }
        public virtual Face Face3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces31 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces41 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces111 { get; set; }
        public virtual Face Face4 { get; set; }
        public virtual Face Face12 { get; set; }
        public virtual Face Face22 { get; set; }
        public virtual Face Face31 { get; set; }
        public virtual Face Face41 { get; set; }
        public virtual Face Face5 { get; set; }
        public virtual Face Face6 { get; set; }
        public virtual Face Face7 { get; set; }
        public virtual Face Face8 { get; set; }
        public virtual Face Face9 { get; set; }
        public virtual Face Face10 { get; set; }
        public virtual Face Face111 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces32 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces42 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces51 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces61 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces71 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces81 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces91 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces101 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces112 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces121 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces131 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces141 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces211 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces221 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces231 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces24 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces25 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces26 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces27 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces28 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces29 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces30 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces311 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces321 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces33 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces34 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces35 { get; set; }
        public virtual Face Face13 { get; set; }
        public virtual Face Face14 { get; set; }
        public virtual Face Face23 { get; set; }
        public virtual Face Face32 { get; set; }
        public virtual Face Face42 { get; set; }
        public virtual Face Face51 { get; set; }
        public virtual Face Face61 { get; set; }
        public virtual Face Face71 { get; set; }
        public virtual Face Face81 { get; set; }
        public virtual Face Face91 { get; set; }
        public virtual Face Face101 { get; set; }
        public virtual Face Face112 { get; set; }
        public virtual Face Face121 { get; set; }
        public virtual Face Face131 { get; set; }
        public virtual Face Face141 { get; set; }
        public virtual Face Face15 { get; set; }
        public virtual Face Face16 { get; set; }
        public virtual Face Face17 { get; set; }
        public virtual Face Face18 { get; set; }
        public virtual Face Face19 { get; set; }
        public virtual Face Face20 { get; set; }
        public virtual Face Face211 { get; set; }
        public virtual Face Face221 { get; set; }
        public virtual Face Face231 { get; set; }
        public virtual Face Face24 { get; set; }
        public virtual Face Face25 { get; set; }
        public virtual Face Face26 { get; set; }
        public virtual Face Face27 { get; set; }
        public virtual Face Face28 { get; set; }
        public virtual Face Face29 { get; set; }
        public virtual Face Face30 { get; set; }
        public virtual Face Face311 { get; set; }
        public virtual Face Face321 { get; set; }
        public virtual Face Face33 { get; set; }
        public virtual Face Face34 { get; set; }
        public virtual Face Face35 { get; set; }
    }
}
